---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: brewz
spec:
  host: brewz.f5demos.com
  tls:
    secret: f5demos-wildcard-tls-secret
    redirect:
      enable: true
  upstreams:
    - name: spa
      service: spa
      port: 8080
    - name: api
      service: api
      port: 8000
    - name: inventory
      service: inventory
      port: 8002
    - name: recommendations
      service: recommendations
      port: 8001
    - name: spa-dark
      service: spa-dark
      port: 8080
    - name: checkout
      service: checkout
      port: 8003
  routes:
    - path: /
      matches:
        - conditions:
          - cookie: "app_version"
            value: "dark"
          action:
            pass: spa-dark
      action:
        pass: spa
    - path: /api
      policies:
        - name: rate-limit-policy
      action:
        pass: api
    - path: /api/inventory
      action:
        proxy:
          upstream: inventory
          rewritePath: /api/inventory
    - path: /api/recommendations
      action:
        proxy:
          upstream: recommendations
          rewritePath: /api/recommendations
    - path: /images
      action:
        proxy:
          upstream: api
          rewritePath: /images
    - path: /api/order
      policies:
        - name: jwt-policy
      action:
        proxy:
          upstream: checkout
          rewritePath: /api/order
      errorPages:
        - codes: [401]
          return:
            code: 401
            type: application/json
            body: |
              {\"msg\": \"Authorization Required\"}
            headers:
              - name: x-debug-original-status
                value: ${upstream_status}
