apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-plus-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    path: charts/nginx-plus-ingress
    repoURL: https://github.com/aknot242/modern_app_jumpstart_workshop.git
    targetRevision: HEAD
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
